sonar.projectKey=hardwaretrack
sonar.projectName=HardwareTrack
sonar.sources=backend
sonar.exclusions=**/test_*.py,**/conftest.py
sonar.tests=backend
sonar.test.inclusions=**/test_*.py
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.host.url=http://localhost:9000
