sonar.projectKey=hardwaretrack
sonar.projectName=HardwareTrack
sonar.sources=backend
sonar.exclusions=backend/tests/**,backend/test_main.py,backend/conftest.py
sonar.tests=backend
sonar.test.inclusions=backend/tests/**,backend/test_main.py,backend/conftest.py
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.language=py
sonar.sourceEncoding=UTF-8
